QUALITIES = {
    "Normal": 0,
    "0": "Normal",
    "Genuine": 1,
    "1": "Genuine",
    "rarity2": 2,
    "2": "rarity2",
    "Vintage": 3,
    "3": "Vintage",
    "rarity3": 4,
    "4": "rarity3",
    "Unusual": 5,
    "5": "Unusual",
    "Unique": 6,
    "6": "Unique",
    "Community": 7,
    "7": "Community",
    "Valve": 8,
    "8": "Valve",
    "Self-Made": 9,
    "9": "Self-Made",
    "Customized": 10,
    "10": "Customized",
    "Strange": 11,
    "11": "Strange",
    "Completed": 12,
    "12": "Completed",
    "Haunted": 13,
    "13": "Haunted",
    "Collector's": 14,
    "14": "Collector's",
    "Decorated Weapon": 15,
    "15": "Decorated Weapon",
}

KILLSTREAKS = {
    "Basic": 1,
    "1": "Basic",
    "Specialized": 2,
    "2": "Specialized",
    "Professional": 3,
    "3": "Professional",
}

KILLSTREAKERS = {
    "2002": "Fire Horns",
    "Fire Horns": 2002,
    "2003": "Cerebral Discharge",
    "Cerebral Discharge": 2003,
    "2004": "Tornado",
    "Tornado": 2004,
    "2005": "Flames",
    "Flames": 2005,
    "2006": "Singularity",
    "Singularity": 2006,
    "2007": "Incinerator",
    "Incinerator": 2007,
    "2008": "Hypno-Beam",
    "Hypno-Beam": 2008,
}

SHEENS = {
    "1": "Team Shine",
    "Team Shine": 1,
    "2": "Deadly Daffodil",
    "Deadly Daffodil": 2,
    "3": "Manndarin",
    "Manndarin": 3,
    "4": "Mean Green",
    "Mean Green": 4,
    "5": "Agonizing Emerald",
    "Agonizing Emerald": 5,
    "6": "Villainous Violet",
    "Villainous Violet": 6,
    "7": "Hot Rod",
    "Hot Rod": 7,
}

SPELLS = {
    "1006": "Voices From Below",
    "Voices From Below": 1006,
    "1007": "Pumpkin Bombs",
    "Pumpkin Bombs": 1007,
    "1008": "Halloween Fire",
    "Halloween Fire": 1008,
    "1009": "Exorcism",
    "Exorcism": 1009,
    "8900": "Putrescent Pigmentation",
    "Putrescent Pigmentation": 8900,
    "8901": "Die Job",
    "Die Job": 8901,
    "8902": "Chromatic Corruption",
    "Chromatic Corruption": 8902,
    "8903": "Spectral Spectrum",
    "Spectral Spectrum": 8903,
    "8904": "Sinister Staining",
    "Sinister Staining": 8904,
    "8914": "Team Spirit Footprints",
    "Team Spirit Footprints": 8914,
    "8915": "Gangreen Footprints",
    "Gangreen Footprints": 8915,
    "8916": "Corpse Gray Footprints",
    "Corpse Gray Footprints": 8916,
    "8917": "Violent Violet Footprints",
    "Violent Violet Footprints": 8917,
    "8918": "Rotten Orange Footprints",
    "Rotten Orange Footprints": 8918,
    "8919": "Bruised Purple Footprints",
    "Bruised Purple Footprints": 8919,
    "8920": "Headless Horseshoes",
    "Headless Horseshoes": 8920,
}

PARTS = {
    "2": "Kill Assists",
    "Kill Assists": 2,
    "10": "Scouts Killed",
    "Scouts Killed": 10,
    "11": "Snipers Killed",
    "Snipers Killed": 11,
    "12": "Soldiers Killed",
    "Soldiers Killed": 12,
    "13": "Demomen Killed",
    "Demomen Killed": 13,
    "14": "Heavies Killed",
    "Heavies Killed": 14,
    "15": "Pyros Killed",
    "Pyros Killed": 15,
    "16": "Spies Killed",
    "Spies Killed": 16,
    "17": "Engineers Killed",
    "Engineers Killed": 17,
    "18": "Medics Killed",
    "Medics Killed": 18,
    "19": "Buildings Destroyed",
    "Buildings Destroyed": 19,
    "20": "Projectiles Reflected",
    "Projectiles Reflected": 20,
    "21": "Headshot Kills",
    "Headshot Kills": 21,
    "22": "Airborne Enemy Kills",
    "Airborne Enemy Kills": 22,
    "23": "Gib Kills",
    "Gib Kills": 23,
    "27": "Kills Under A Full Moon",
    "Kills Under A Full Moon": 27,
    "28": "Dominations",
    "Dominations": 28,
    "30": "Revenges",
    "Revenges": 30,
    "31": "Posthumous Kills",
    "Posthumous Kills": 31,
    "32": "Teammates Extinguished",
    "Teammates Extinguished": 32,
    "33": "Critical Kills",
    "Critical Kills": 33,
    "34": "Kills While Explosive-Jumping",
    "Kills While Explosive-Jumping": 34,
    "36": "Sappers Destroyed",
    "Sappers Destroyed": 36,
    "37": "Cloaked Spies Killed",
    "Cloaked Spies Killed": 37,
    "38": "Medics Killed That Have Full ÜberCharge",
    "Medics Killed That Have Full ÜberCharge": 38,
    "39": "Robots Destroyed",
    "Robots Destroyed": 39,
    "40": "Giant Robots Destroyed",
    "Giant Robots Destroyed": 40,
    "44": "Kills While Low Health",
    "Kills While Low Health": 44,
    "45": "Kills During Halloween",
    "Kills During Halloween": 45,
    "46": "Robots Killed During Halloween",
    "Robots Killed During Halloween": 46,
    "47": "Defender Kills",
    "Defender Kills": 47,
    "48": "Submerged Enemy Kills",
    "Submerged Enemy Kills": 48,
    "49": "Kills While Übercharged",
    "Kills While Übercharged": 49,
    "61": "Tanks Destroyed",
    "Tanks Destroyed": 61,
    "62": "Long-Distance Kills",
    "Long-Distance Kills": 62,
    "67": "Kills during Victory Time",
    "Kills during Victory Time": 67,
    "68": "Robot Scouts Destroyed",
    "Robot Scouts Destroyed": 68,
    "74": "Robot Spies Destroyed",
    "Robot Spies Destroyed": 74,
    "77": "Taunt Kills",
    "Taunt Kills": 77,
    "78": "Unusual-Wearing Player Kills",
    "Unusual-Wearing Player Kills": 78,
    "79": "Burning Player Kills",
    "Burning Player Kills": 79,
    "80": "Killstreaks Ended",
    "Killstreaks Ended": 80,
    "81": "Freezecam Taunt Appearances",
    "Freezecam Taunt Appearances": 81,
    "82": "Damage Dealt",
    "Damage Dealt": 82,
    "83": "Fires Survived",
    "Fires Survived": 83,
    "84": "Allied Healing Done",
    "Allied Healing Done": 84,
    "85": "Point Blank Kills",
    "Point Blank Kills": 85,
    "87": "Kills",
    "Kills": 87,
    "88": "Full Health Kills",
    "Full Health Kills": 88,
    "89": "Taunting Player Kills",
    "Taunting Player Kills": 89,
    "93": "Not Crit nor MiniCrit Kills",
    "Not Crit nor MiniCrit Kills": 93,
    "94": "Player Hits",
    "Player Hits": 94,
    "95": "Assists",
    "Assists": 95,
    "97": "Kills",
}

PAINTS = {
    "654740": "An Air of Debonair",
    "An Air of Debonair": "654740",
    "28394D": "An Air of Debonair",
    "3B1F23": "Balaclavas Are Forever",
    "Balaclavas Are Forever": "3B1F23",
    "18233D": "Balaclavas Are Forever",
    "C36C2D": "Cream Spirit",
    "Cream Spirit": "C36C2D",
    "B88035": "Cream Spirit",
    "483838": "Operator's Overalls",
    "Operator's Overalls": "483838",
    "384248": "Operator's Overalls",
    "B8383B": "Team Spirit",
    "Team Spirit": "B8383B",
    "5885A2": "Team Spirit",
    "803020": "The Value of Teamwork",
    "The Value of Teamwork": "803020",
    "256D8D": "The Value of Teamwork",
    "A89A8C": "Waterlogged Lab Coat",
    "Waterlogged Lab Coat": "A89A8C",
    "839FA3": "Waterlogged Lab Coat",
    "2F4F4F": "A Color Similar to Slate",
    "A Color Similar to Slate": "2F4F4F",
    "7D4071": "A Deep Commitment to Purple",
    "A Deep Commitment to Purple": "7D4071",
    "141414": "A Distinctive Lack of Hue",
    "A Distinctive Lack of Hue": "141414",
    "BCDDB3": "A Mann's Mint",
    "A Mann's Mint": "BCDDB3",
    "2D2D24": "After Eight",
    "After Eight": "2D2D24",
    "7E7E7E": "Aged Moustache Grey",
    "Aged Moustache Grey": "7E7E7E",
    "E6E6E6": "An Extraordinary Abundance of Tinge",
    "An Extraordinary Abundance of Tinge": "E6E6E6",
    "E7B53B": "Australium Gold",
    "Australium Gold": "E7B53B",
    "D8BED8": "Color No. 216-190-216",
    "Color No. 216-190-216": "D8BED8",
    "E9967A": "Dark Salmon Injustice",
    "Dark Salmon Injustice": "E9967A",
    "808000": "Drably Olive",
    "Drably Olive": "808000",
    "729E42": "Indubitably Green",
    "Indubitably Green": "729E42",
    "CF7336": "Mann Co. Orange",
    "Mann Co. Orange": "CF7336",
    "A57545": "Muskelmannbraun",
    "Muskelmannbraun": "A57545",
    "51384A": "Noble Hatter's Violet",
    "Noble Hatter's Violet": "51384A",
    "C5AF91": "Peculiarly Drab Tincture",
    "Peculiarly Drab Tincture": "C5AF91",
    "FF69B4": "Pink as Hell",
    "Pink as Hell": "FF69B4",
    "694D3A": "Radigan Conagher Brown",
    "Radigan Conagher Brown": "694D3A",
    "32CD32": "The Bitter Taste of Defeat and Lime",
    "The Bitter Taste of Defeat and Lime": "32CD32",
    "F0E68C": "The Color of a Gentlemann's Business Pants",
    "The Color of a Gentlemann's Business Pants": "F0E68C",
    "7C6C57": "Ye Olde Rustic Colour",
    "Ye Olde Rustic Colour": "7C6C57",
    "424F3B": "Zepheniah's Greed",
    "Zepheniah's Greed": "424F3B",
}

WEARS = {
    "Factory New": 1,
    "1": "Factory New",
    "Minimal Wear": 2,
    "2": "Minimal Wear",
    "Field-Tested": 3,
    "3": "Field-Tested",
    "Well-Worn": 4,
    "4": "Well-Worn",
    "Battle Scarred": 5,
    "5": "Battle Scarred",
}


COLORS = {
    "Genuine": "4D7455",
    "1": "4D7455",
    "Vintage": "476291",
    "3": "476291",
    "Unusual": "8650AC",
    "5": "8650AC",
    "Unique": "7D6D00",
    "6": "7D6D00",
    "Strange": "CF6A32",
    "11": "CF6A32",
    "Haunted": "38F3AB",
    "13": "38F3AB",
    "Collector's": "AA0000",
    "14": "AA0000",
    "Decorated Weapon": "FAFAFA",
    "15": "FAFAFA",
}

EYES = KILLSTREAKERS
EXTERIORS = WEARS
STRANGE_PARTS = PARTS
QUALITY_COLORS = COLORS
HALLOWEEN_SPELLS = SPELLS
KILLSTREAK_TIERS = KILLSTREAKS
